# Generated by Django 6.0.3 on 2026-04-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_paid_at_payment_advance_paid_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
