# Generated by Django 5.2 on 2026-04-04 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_alter_bid_id_alter_job_id'),
        ('payment', '0003_delete_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('provider_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_paid', models.BooleanField(default=False)),
                ('advance_paid_at', models.DateTimeField(blank=True, null=True)),
                ('advance_ref_id', models.CharField(blank=True, max_length=200, null=True)),
                ('advance_transaction_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('final_paid', models.BooleanField(default=False)),
                ('final_paid_at', models.DateTimeField(blank=True, null=True)),
                ('final_ref_id', models.CharField(blank=True, max_length=200, null=True)),
                ('final_transaction_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('esewa', 'E-Sewa'), ('cash', 'Cash')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('advance_paid', '20% Advance Paid'), ('full_paid', '100% Paid'), ('held', 'Held by Platform'), ('released', 'Released to Provider'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='jobs.job')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
