# Generated by Django 6.0.3 on 2026-04-03 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('service_provider', 'Service Provider'), ('admin', 'Admin')], default='client', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_number', models.CharField(max_length=100)),
                ('citizenship_image', models.ImageField(upload_to='kyc/citizenship/')),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_image', models.ImageField(blank=True, null=True, upload_to='kyc/pan/')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='kyc/license/')),
                ('issuing_authority', models.CharField(blank=True, max_length=255, null=True)),
                ('license_valid_until', models.DateField(blank=True, null=True)),
                ('certificate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='kyc/certificate/')),
                ('training_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='kyc/insurance/')),
                ('insurance_valid_until', models.DateField(blank=True, null=True)),
                ('years_experience', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='providers', to='categories.category')),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to='users.customuser')),
            ],
        ),
    ]
